[[constraint]]
  branch = "parse-constraints-with-dash-in-pre"
  name = "github.com/Masterminds/semver"
  source = "https://github.com/carolynvs/semver.git"

[[constraint]]
  name = "github.com/Masterminds/vcs"
  version = "1.11.0"

[[constraint]]
  name = "github.com/go-yaml/yaml"
  version = "2.0.0"

[[constraint]]
  name = "github.com/pelletier/go-toml"
  version = "1.1.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.0.0"

[[constraint]]
  name = "github.com/jmank88/nuts"
  version = "0.3.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
