package dependencies

import (
	"encoding/json"
	"io/ioutil"
	"sort"
	"strings"
)

type Godeps struct {
	Comment    string `json:"_Comment"`
	ImportPath string
	Deps       []Dependency
}

type Dependency struct {
	ImportPath string
	Comment    string `json:",omitempty"`
	Rev        string
}

func (gd Godeps) DumpToFile(fname string) error {
	gd.Comment = "GENERATED BY DEP, DO NOT EDIT"

	sort.Slice(gd.Deps, func(i, j int) bool {
		return strings.Compare(gd.Deps[i].ImportPath, gd.Deps[j].ImportPath) < 0
	})

	js, err := json.MarshalIndent(gd, "", "\t")
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(fname, js, 0644)
	return err
}
